### ISSUE TITLE
Images not loading when SDK is imported via Cocoapods

### ISSUE THREAD

**Issue by akoller-vs** [ticketmaster/iOS-SecureEntrySDK#4]
Now that the project uses image assets, the podspec also needs to be updated to define them via either

http://guides.cocoapods.org/syntax/podspec.html#resources
or
http://guides.cocoapods.org/syntax/podspec.html#resource_bundles

Including via a bundle is safer to avoid name collisions, but will require some refactoring of how the assets are loaded via code.

**Comment by sevensth** [comment]
+1
I got the same issue

**Comment by karlwhite** [comment]
Hi @akoller-vs & @sevensth! This is now fixed in #9. XCAsset resources are now included in Podspec as resources (not bundles) to retain compatibility with non-cocoapods integrations, however if you encounter any filename collisions, please let me know and I'll rework or add filename prefixes.
