### ISSUE TITLE
The error message text may be incorrect in some cases.

### ISSUE THREAD

**Issue by sevensth** [ticketmaster/iOS-SecureEntrySDK#6]
The error message font size may be too small in some cases
https://github.com/ticketmaster/iOS-SecureEntrySDK/pull/5

**Comment by karlwhite** [comment]
Hi @sevensth, thanks for submitting your PR. I have merged this, so you should see the fix in /master (but not the latest 1.0.4 release). Quick note: this bug would likely only occur if you are sizing the SecureEntryView smaller than the guidelines recommend, so if you're unaware of this you may want to double-check your view's sizing/placement.

**Comment by sevensth** [comment]
Thanks @karlwhite
