### ISSUE TITLE
Swift version is set to 4.2 in podspec causing building failure

### ISSUE THREAD

**Issue by sevensth** [ticketmaster/iOS-SecureEntrySDK#8]
Can't build current code under swift 4.2, because the error:
`SecureEntryView.swift:333:65: error: 'kCAFilterNearest' has been renamed to 'CALayerContentsFilter.nearest'`

Please update the podspec to use swift 4.0 or use `CALayerContentsFilter.nearest` instead of `kCAFilterNearest`

**Comment by karlwhite** [comment]
Hey @sevensth, thanks for reporting this! This has now been fixed in #9
